language: android
android:
   components:
   - platform-tools
   - android-23
   - build-tools-23.0.0
   - extra
   
env:
  global:
    MALLOC_ARENA_MAX=2
   
jdk: oraclejdk7

sudo: false

notifications:
  email: false

addons:
  apt:
    packages:
    - libgd2-xpm
    - ia32-libs
    - ia32-libs-multiarch

script:
  - chmod a+x gradlew
  - ./gradlew clean build --stacktrace