language: android

jdk: oraclejdk8

sudo: false

android:
  components:
    - tools
    - android-27
    - build-tools-27.0.3
    - platform-tools
    - extra-google-m2repository
    - extra-android-m2repository
    - extra-google-google_play_services

before_cache:
  - rm -rf  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -rf $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
    - $HOME/.android/build-cache

env:
  global:
    MALLOC_ARENA_MAX=1
   
install:
  - ulimit -s 1082768
  - touch app/keys.properties

script:
  - ./gradlew build
  - ./gradlew assembleStandardRelease --stacktrace

after_failure:
  # tests
  - cat app/build/reports/tests/testDebugUnitTest/index.html
  # app
  - cat app/build/reports/lint-results.xml
  - cat app/build/reports/lint-results.html
