language: android

android:
  components:
    - tools
    - android-26
    - build-tools-26.0.1
    - platform-tools
    - extra-google-m2repository

before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock

cache:
    directories:
      - "${TRAVIS_BUILD_DIR}/gradle/caches/"
      - "${TRAVIS_BUILD_DIR}/gradle/wrapper/dists/"
      - "$HOME/.gradle/caches/"
      - "$HOME/.gradle/wrapper/"

env:
  global:
    MALLOC_ARENA_MAX=1
   
jdk: oraclejdk8

sudo: false

install:
  - ulimit -s 1082768
  - touch app/keys.properties
  - printf 'GooglePlayLicenseKey="GooglePlayLicenseKey"\nIapProductKey="IapProductKey"\ncc="cc"\nii="ii"' > app/keys.properties

script:
  - ./gradlew build
  - ./gradlew assembleTravisRelease --stacktrace

after_failure:
  # tests
  - cat app/build/reports/tests/testDebugUnitTest/index.html
  # app
  - cat app/build/reports/lint-results.xml
  - cat app/build/reports/lint-results.html
